"""Validation execution engine.

REWRITE v5 - Added execute_agent_query for ReAct (Reason + Act) Agentic Loops.
Maintains backward compatibility for static JSON configuration rules.
"""
import re
import logging
from typing import List, Dict, Any, Optional
from datetime import datetime
import time

import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

from app.agents.state import ValidationRule, ValidationResult

logger = logging.getLogger(__name__)


class ValidationEngine:
    """Engine for executing validation rules and agent queries."""
    
    def __init__(self):
        self.execution_logs = []
    
    def _apply_prep_transformation(self, df: pd.DataFrame, data_source_info: Any) -> pd.DataFrame:
        """Apply Phase 6 Prep transformations: Rename and Subset."""
        if not data_source_info:
            return df
            
        mapping = getattr(data_source_info, 'column_mapping', None)
        selected = getattr(data_source_info, 'selected_columns', None)
        
        # 1. Rename columns
        if mapping:
            # Only rename if column exists in mapping
            # Note: mapping is original -> new
            df = df.rename(columns=mapping)
            self.execution_logs.append({
                "role": "system",
                "content": f"[Prep] Applied column mapping/renaming: {len(mapping)} columns mapped."
            })
            
        # 2. Filter to selected columns
        if selected:
            # Only keep columns that are in 'selected' list AND exist in df
            existing_selected = [c for c in selected if c in df.columns]
            df = df[existing_selected]
            self.execution_logs.append({
                "role": "system",
                "content": f"[Prep] Filtered to {len(existing_selected)} selected columns for analysis."
            })
            
        return df
    
    # ==========================================
    # NEW AGENTIC EXECUTION ENGINE
    # ==========================================

    async def execute_agent_query(
        self, 
        query: str, 
        query_type: str, 
        data_source_info: Any, 
        sample_data: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Executes a raw SQL or Pandas query generated by the autonomous agent.
        Safely runs the query against an in-memory sandbox of the sample data.
        """
        logger.info(f"ValidationEngine.execute_agent_query: Running {query_type.upper()} query.")
        
        try:
            if not query or str(query).strip() == "" or str(query).lower() == "none":
                return {"status": "error", "error": "Agent provided an empty or null query. Please formulate a valid SQL or Pandas query string."}

            if not sample_data:
                return {"status": "error", "error": "No sample data available to query."}
            
            # Load the data into a Pandas DataFrame
            df = pd.DataFrame(sample_data)
            
            # Apply Phase 6 transformations if any
            df = self._apply_prep_transformation(df, data_source_info)
            
            # Extract clean table name from path (e.g. 'public.sales' -> 'sales')
            target_path = getattr(data_source_info, 'target_path', 'target_table')
            table_name = target_path.split('.')[-1]
            
            if query_type.lower() == 'sql':
                # Create an in-memory SQLite database to securely sandbox the agent's query
                sqlite_engine = create_engine("sqlite:///:memory:")
                
                # Register the dataframe as a SQL table using the actual table name
                df.to_sql(table_name, sqlite_engine, index=False)
                
                # Also register 'target_table' as an alias in case the LLM uses the literal word "target_table"
                if table_name != "target_table":
                    df.to_sql("target_table", sqlite_engine, index=False)
                
                with sqlite_engine.connect() as conn:
                    result = conn.execute(text(query))
                    
                    if result.returns_rows:
                        # Fetch all rows to get the count, but only return a sample to the LLM to save tokens
                        all_rows = [dict(row._mapping) for row in result.fetchall()]
                        row_count = len(all_rows)
                        
                        # Clean NaN/NaT values so the result is safely JSON serializable
                        sample_rows = []
                        for row in all_rows[:5]:  # Return top 5 examples
                            cleaned_row = {}
                            for k, v in row.items():
                                if pd.isna(v):
                                    cleaned_row[k] = None
                                else:
                                    cleaned_row[k] = v
                            sample_rows.append(cleaned_row)
                            
                        return {
                            "status": "success",
                            "row_count": row_count,
                            "sample_rows": sample_rows
                        }
                    else:
                        return {
                            "status": "success",
                            "row_count": 0,
                            "sample_rows": [],
                            "message": "Query executed successfully but returned no rows."
                        }
            
            elif query_type.lower() == 'pandas':
                # Fallback for pandas expressions if the LLM chooses to write pandas code
                local_vars = {"df": df, "pd": pd, "np": np}
                try:
                    # Restricted eval execution
                    result = eval(query, {"__builtins__": {}}, local_vars)
                    
                    if isinstance(result, pd.DataFrame):
                        records = result.replace({pd.NA: None, pd.NaT: None}).to_dict('records')
                        return {
                            "status": "success",
                            "row_count": len(records),
                            "sample_rows": records[:5]
                        }
                    elif isinstance(result, pd.Series):
                        return {
                            "status": "success",
                            "row_count": len(result),
                            "sample_rows": result.head(5).tolist()
                        }
                    else:
                        return {
                            "status": "success",
                            "row_count": 1,
                            "sample_rows": [result]
                        }
                except Exception as e:
                    return {"status": "error", "error": f"Pandas execution error: {str(e)}"}
            
            else:
                return {"status": "error", "error": f"Unsupported query_type: {query_type}"}
                
        except Exception as e:
            error_msg = str(e)
            logger.error(f"Agent query execution failed: {error_msg}")
            return {
                "status": "error", 
                "error": error_msg,
                "query": query,
                "query_type": query_type
            }

    # ==========================================
    # LEGACY STATIC RULE EXECUTION (For Custom Rules)
    # ==========================================
    
    async def execute_rules(
        self,
        rules: List[ValidationRule],
        sample_data: List[Dict[str, Any]],
        schema: Optional[Dict[str, Any]] = None,
        data_source_info: Optional[Any] = None,
    ) -> List[ValidationResult]:
        """Execute all validation rules."""
        logger.info(f"ValidationEngine.execute_rules called with {len(rules)} rules")
        
        if not sample_data:
            logger.warning("No sample data provided for validation")
            return []
        
        # Setup SQL Pushdown Engine if applicable
        self.sql_connector = None
        self.target_table = None
        sql_pushdown_enabled = False

        if data_source_info and getattr(data_source_info, 'full_scan_requested', False):
            source_type = str(getattr(data_source_info, 'source_type', '')).lower()
            if source_type in ['postgresql', 'postgres', 'mysql', 'sqlite']:
                try:
                    from app.connectors.factory import ConnectorFactory
                    self.sql_connector = ConnectorFactory.create_connector(source_type, data_source_info.connection_config)
                    await self.sql_connector.connect()
                    self.target_table = data_source_info.target_path
                    sql_pushdown_enabled = True
                    self.execution_logs.append({
                        "role": "system",
                        "content": f"[Engine] Enabled Dual-Engine SQL Pushdown for {source_type} table: {self.target_table}"
                    })
                except Exception as e:
                    logger.warning(f"Failed to initialize SQL pushdown: {e}")
                    self.execution_logs.append({
                        "role": "warning",
                        "content": f"[Engine] Failed to initialize SQL pushdown, falling back to pandas memory processing: {e}"
                    })

        # Convert to DataFrame for fallback processing
        df = None
        if not sql_pushdown_enabled or any(r.rule_type != 'custom_sql' for r in rules):
            df = pd.DataFrame(sample_data)
            
            # Apply Phase 6 transformations if any
            df = self._apply_prep_transformation(df, data_source_info)
            
            # Apply slicing filters to the pandas dataframe if provided
            slice_filters = getattr(data_source_info, 'slice_filters', None) if data_source_info else None
            if slice_filters:
                try:
                    for col, val in slice_filters.items():
                        if isinstance(val, str):
                            df = df[df[col] == val]
                        else:
                            df = df[df[col] == val]
                    self.execution_logs.append({
                        "role": "system",
                        "content": f"[Engine] Applied UI Slice Filters: {slice_filters}. Pandas subsets to {len(df)} rows."
                    })
                except Exception as e:
                    logger.warning(f"Failed to apply slice_filters to Pandas dataframe: {e}")
            
            self.execution_logs.append({
                "role": "system",
                "content": f"[Engine] Initialized Pandas fallback with {len(df)} sample rows."
            })
            logger.info(f"DataFrame created with {len(df)} rows after slicing")
        
        results = []
        for i, rule in enumerate(rules, 1):
            try:
                logger.info(f"  Executing rule {i}/{len(rules)}: {rule.name}")
                start_time = time.time()
                result = None
                
                # Try SQL Pushdown first
                if sql_pushdown_enabled and self.sql_connector:
                    result = await self._execute_sql_rule(rule)
                
                # Fallback to Pandas if not pushed down
                if result is None:
                    if df is None:
                        df = pd.DataFrame(sample_data)
                    result = await self._execute_rule(rule, df)
                    
                execution_time = int((time.time() - start_time) * 1000)
                result.execution_time_ms = execution_time
                results.append(result)
                logger.info(f"    Result: {result.status} ({result.passed_count} passed, {result.failed_count} failed)")
            except Exception as e:
                logger.error(f"Rule execution failed for {rule.name}: {str(e)}")
                results.append(ValidationResult(
                    rule_id=rule.id or "unknown",
                    rule_name=rule.name,
                    status="error",
                    passed_count=0,
                    failed_count=len(sample_data),
                    ai_insights=f"Execution error: {str(e)}",
                    severity=rule.severity,
                    rule_type=rule.rule_type,
                ))
        
        if getattr(self, 'sql_connector', None):
            try:
                await self.sql_connector.disconnect()
            except Exception as e:
                pass
                
        logger.info(f"ValidationEngine returning {len(results)} results")
        return results
    
    async def _execute_sql_rule(self, rule: ValidationRule) -> Optional[ValidationResult]:
        """Convert a standard rule into a direct SQL query and execute against the DB."""
        if not self.sql_connector or not self.target_table:
            return None
            
        rule_type = rule.rule_type.lower()
        config = rule.config
        
        self.execution_logs.append({
            "role": "assistant",
            "content": f"[SQL Pushdown] Translating {rule_type} rule: {rule.name} into SQL"
        })
        
        try:
            query = None
            
            # Special Custom SQL passthrough
            if rule_type == 'custom_sql' and 'query' in config:
                query = config['query']
                
            # Column Rules
            elif rule_type == 'column' and rule.target_columns:
                col = f'"{rule.target_columns[0]}"'
                if rule.name == "customer_id_unique" or "unique" in rule.name.lower():
                    # Find duplicates using GROUP BY HAVING
                    query = f"""
                        SELECT * FROM {self.target_table} 
                        WHERE {col} IN (
                            SELECT {col} FROM {self.target_table} GROUP BY {col} HAVING COUNT(*) > 1
                        )
                    """
                elif "null" in rule.name.lower() or "missing" in rule.name.lower():
                    query = f"SELECT * FROM {self.target_table} WHERE {col} IS NULL"
                elif 'min_value' in config and 'max_value' in config:
                    query = f"SELECT * FROM {self.target_table} WHERE {col} < {config['min_value']} OR {col} > {config['max_value']}"
                elif 'min_value' in config:
                    query = f"SELECT * FROM {self.target_table} WHERE {col} < {config['min_value']}"
                elif 'max_value' in config:
                    query = f"SELECT * FROM {self.target_table} WHERE {col} > {config['max_value']}"
            
            if not query:
                self.execution_logs.append({
                    "role": "warning",
                    "content": f"[SQL Pushdown] Rule type ({rule_type}) or syntax ({rule.name}) not yet supported for direct SQL translation. Falling back."
                })
                return None
                
            self.execution_logs.append({
                "role": "assistant",
                "content": f"[SQL Pushdown] Executing query: {query}"
            })
            
            # Use SQLAlchemy connection directly if available
            if hasattr(self.sql_connector, '_engine') and self.sql_connector._engine:
                start_q = time.time()
                with self.sql_connector._engine.connect() as conn:
                    result = conn.execute(text(query))
                    failure_rows = [dict(row._mapping) for row in result.fetchmany(10)]
                    failed_count = result.rowcount if hasattr(result, 'rowcount') and result.rowcount > 0 else len(failure_rows)
                    if failed_count <= 0 and len(failure_rows) > 0:
                         failed_count = len(failure_rows) 
                         
                total_rows = await self.sql_connector.get_row_count(self.target_table)
                passed_count = total_rows - failed_count
                
                self.execution_logs.append({
                    "role": "system",
                    "content": f"[SQL Pushdown] Query OK in {int((time.time() - start_q)*1000)}ms. {failed_count} failures found."
                })
                
                mock_df = pd.DataFrame(failure_rows)
                failed_mask = pd.Series([True] * len(mock_df))
                duplicate_col = rule.target_columns[0] if ("unique" in rule.name.lower()) else None
                
                res = self._create_result(rule, mock_df, failed_mask, duplicate_col=duplicate_col)
                res.passed_count = passed_count
                res.failed_count = failed_count
                return res
            else:
                return None
                
        except Exception as e:
            self.execution_logs.append({
                "role": "error",
                "content": f"[SQL Pushdown] Error executing query: {e}"
            })
            logger.error(f"SQL Pushdown execution failed: {e}")
            return None

    async def _execute_rule(self, rule: ValidationRule, df: pd.DataFrame) -> ValidationResult:
        """Execute a single validation rule."""
        rule_type = rule.rule_type.lower()
        
        self.execution_logs.append({
            "role": "assistant",
            "content": f"[Engine] Executing {rule_type} rule: {rule.name} (Target: {rule.target_columns})"
        })

        if rule_type == "column":
            return await self._execute_column_rule(rule, df)
        elif rule_type == "row":
            return await self._execute_row_rule(rule, df)
        elif rule_type == "table":
            return await self._execute_table_rule(rule, df)
        elif rule_type == "statistical":
            return await self._execute_statistical_rule(rule, df)
        elif rule_type == "pattern":
            return await self._execute_pattern_rule(rule, df)
        elif rule_type == "validity":
            return await self._execute_column_rule(rule, df)
        elif rule_type == "custom_sql":
            return await self._execute_custom_sql_rule(rule, df)
        else:
            raise ValueError(f"Unknown rule type: {rule_type}")
    
    async def _execute_column_rule(self, rule: ValidationRule, df: pd.DataFrame) -> ValidationResult:
        """Execute column-level validation rule."""
        config = rule.config
        target_columns = rule.target_columns

        if not target_columns:
            raise ValueError("Column rule requires target_columns")

        column = target_columns[0]
        if column not in df.columns:
            return self._create_result(rule, df, pd.Series([True] * len(df)), 
                                       error_msg=f"Column '{column}' not found in data")

        col_data = df[column]
        failed_mask = pd.Series([False] * len(df))

        # Special handling for specific rule names
        duplicate_col = None
        if rule.name == "customer_id_unique" or "unique" in rule.name.lower():
            duplicated_mask = col_data.duplicated(keep=False)
            failed_mask |= duplicated_mask
            duplicate_col = column
        elif rule.name == "email_format" or "format" in rule.name.lower():
            if 'pattern' in config:
                try:
                    matches = col_data.astype(str).str.match(config['pattern'], na=False)
                    failed_mask |= ~matches
                except:
                    failed_mask |= True
        elif rule.name == "phone_length" or "phone" in rule.name.lower():
            if 'pattern' in config:
                try:
                    matches = col_data.astype(str).str.match(config['pattern'], na=False)
                    failed_mask |= ~matches
                except:
                    failed_mask |= True
            elif 'min_length' in config or 'max_length' in config:
                str_data = col_data.astype(str)
                lengths = str_data.str.len()
                if 'min_length' in config:
                    failed_mask |= lengths < config['min_length']
                if 'max_length' in config:
                    failed_mask |= lengths > config['max_length']
        elif rule.name == "dob_within_range" or "dob" in rule.name.lower() or "date_of_birth" in rule.name.lower():
            if 'min_age' in config or 'max_age' in config:
                try:
                    dates = pd.to_datetime(col_data, errors='coerce')
                    today = pd.Timestamp.today()
                    
                    if 'min_age' in config:
                        min_date = today - pd.DateOffset(years=config['min_age'])
                        failed_mask |= (dates > min_date) & dates.notna()
                    if 'max_age' in config:
                        max_date = today - pd.DateOffset(years=config['max_age'])
                        failed_mask |= (dates < max_date) & dates.notna()
                except:
                    failed_mask |= col_data.notna()
        elif rule.name == "lifetime_value_positive" or "lifetime" in rule.name.lower():
            try:
                numeric_data = pd.to_numeric(col_data, errors='coerce')
                if 'min' in config:
                    failed_mask |= numeric_data < config['min']
                else:
                    failed_mask |= numeric_data < 0
            except:
                failed_mask |= col_data.notna()
        elif rule.name == "status_not_null" or "status" in rule.name.lower():
            failed_mask |= col_data.isnull()
        elif rule.name == "country_non_empty" or "country" in rule.name.lower():
            failed_mask |= (col_data.isnull()) | (col_data.astype(str) == '')
        else:
            if config.get('check_null', False):
                failed_mask |= col_data.isnull()

            if config.get('check_empty', False):
                failed_mask |= (col_data == '') | (col_data == ' ')

            if 'min' in config or 'max' in config:
                try:
                    numeric_data = pd.to_numeric(col_data, errors='coerce')
                    if 'min' in config:
                        failed_mask |= numeric_data < config['min']
                    if 'max' in config:
                        failed_mask |= numeric_data > config['max']
                except:
                    pass

            if 'min_length' in config or 'max_length' in config:
                str_data = col_data.astype(str)
                lengths = str_data.str.len()
                if 'min_length' in config:
                    failed_mask |= lengths < config['min_length']
                if 'max_length' in config:
                    failed_mask |= lengths > config['max_length']

            if 'allowed_values' in config:
                failed_mask |= ~col_data.isin(config['allowed_values'])

        return self._create_result(rule, df, failed_mask, duplicate_col=duplicate_col)
    
    async def _execute_row_rule(self, rule: ValidationRule, df: pd.DataFrame) -> ValidationResult:
        """Execute row-level validation rule."""
        config = rule.config
        failed_mask = pd.Series([False] * len(df))
        
        duplicate_col = None
        if "unique" in rule.name.lower() or "duplicate" in rule.name.lower():
            if rule.target_columns:
                target_col = rule.target_columns[0]
                if target_col in df.columns:
                    duplicated_mask = df[target_col].duplicated(keep=False)
                    failed_mask |= duplicated_mask
                    duplicate_col = target_col
        elif 'expression' in config:
            try:
                context = {'df': df, 'pd': pd, 'np': np}
                for col in df.columns:
                    context[col] = df[col]
                result = eval(config['expression'], {"__builtins__": {}}, context)
                failed_mask = ~result if isinstance(result, pd.Series) else pd.Series([not result] * len(df))
            except Exception as e:
                logger.error(f"Expression evaluation failed: {str(e)}")
                failed_mask = pd.Series([True] * len(df))
        elif 'column_comparison' in config:
            col1 = config['column_comparison'].get('column1')
            col2 = config['column_comparison'].get('column2')
            operator = config['column_comparison'].get('operator', '==')
            
            if col1 in df.columns and col2 in df.columns:
                if operator == '==':
                    failed_mask = df[col1] != df[col2]
                elif operator == '!=':
                    failed_mask = df[col1] == df[col2]
                elif operator == '>':
                    failed_mask = df[col1] <= df[col2]
                elif operator == '<':
                    failed_mask = df[col1] >= df[col2]
                elif operator == '>=':
                    failed_mask = df[col1] < df[col2]
                elif operator == '<=':
                    failed_mask = df[col1] > df[col2]
        
        return self._create_result(rule, df, failed_mask, duplicate_col=duplicate_col)
    
    async def _execute_table_rule(self, rule: ValidationRule, df: pd.DataFrame) -> ValidationResult:
        """Execute table-level validation rule."""
        config = rule.config
        failed_mask = pd.Series([False] * len(df))

        duplicate_col = None
        if "unique" in rule.name.lower():
            if rule.target_columns:
                target_col = rule.target_columns[0]
                if target_col in df.columns:
                    duplicated_mask = df[target_col].duplicated(keep=False)
                    failed_mask |= duplicated_mask
                    duplicate_col = target_col
        else:
            if 'min_rows' in config:
                if len(df) < config['min_rows']:
                    failed_mask = pd.Series([True] * len(df))

            if 'max_rows' in config:
                if len(df) > config['max_rows']:
                    failed_mask = pd.Series([True] * len(df))

            if 'unique_columns' in config:
                unique_cols = config['unique_columns']
                if all(col in df.columns for col in unique_cols):
                    duplicates = df.duplicated(subset=unique_cols, keep=False)
                    failed_mask |= duplicates

        return self._create_result(rule, df, failed_mask, duplicate_col=duplicate_col)
    
    async def _execute_statistical_rule(self, rule: ValidationRule, df: pd.DataFrame) -> ValidationResult:
        """Execute statistical validation rule."""
        config = rule.config
        target_columns = rule.target_columns

        if not target_columns:
            return self._create_result(rule, df, pd.Series([False] * len(df)))

        column = target_columns[0]
        if column not in df.columns:
            return self._create_result(rule, df, pd.Series([True] * len(df)))

        col_data = df[column]
        failed_mask = pd.Series([False] * len(df))

        if "dob" in rule.name.lower() or "date_of_birth" in rule.name.lower() or "age" in rule.name.lower():
            try:
                dates = pd.to_datetime(col_data, errors='coerce')
                today = pd.Timestamp.today()
                
                min_age = config.get('min_age', 0)
                max_age = config.get('max_age', 120)
                
                ages = (today - dates).dt.days / 365.25
                
                failed_mask |= (ages < min_age) | (ages > max_age) | dates.isna()
            except:
                failed_mask |= col_data.notna()
        elif "lifetime" in rule.name.lower() or "value" in rule.name.lower():
            try:
                numeric_data = pd.to_numeric(col_data, errors='coerce')
                min_val = config.get('min', 0)
                max_val = config.get('max', None)
                
                failed_mask |= (numeric_data < min_val) | numeric_data.isna()
                if max_val is not None:
                    failed_mask |= numeric_data > max_val
            except:
                failed_mask |= col_data.notna()
        else:
            col_data_numeric = pd.to_numeric(col_data, errors='coerce')

            if config.get('detect_outliers', False):
                Q1 = col_data_numeric.quantile(0.25)
                Q3 = col_data_numeric.quantile(0.75)
                IQR = Q3 - Q1
                lower_bound = Q1 - 1.5 * IQR
                upper_bound = Q3 + 1.5 * IQR
                failed_mask |= (col_data_numeric < lower_bound) | (col_data_numeric > upper_bound)

            if 'zscore_threshold' in config:
                mean = col_data_numeric.mean()
                std = col_data_numeric.std()
                if std > 0:
                    z_scores = (col_data_numeric - mean).abs() / std
                    failed_mask |= z_scores > config['zscore_threshold']
            
            if 'min' in config or 'max' in config:
                if 'min' in config:
                    failed_mask |= col_data_numeric < config['min']
                if 'max' in config:
                    failed_mask |= col_data_numeric > config['max']

        return self._create_result(rule, df, failed_mask)
    
    async def _execute_pattern_rule(self, rule: ValidationRule, df: pd.DataFrame) -> ValidationResult:
        """Execute pattern validation rule."""
        config = rule.config
        target_columns = rule.target_columns

        if not target_columns:
            return self._create_result(rule, df, pd.Series([False] * len(df)))

        column = target_columns[0]
        if column not in df.columns:
            return self._create_result(rule, df, pd.Series([True] * len(df)))

        col_data = df[column].astype(str)
        failed_mask = pd.Series([False] * len(df))

        if 'pattern' in config:
            pattern = config['pattern']
            try:
                matches = col_data.str.match(pattern, na=False)
                if config.get('invert', False):
                    failed_mask |= matches
                else:
                    failed_mask |= ~matches
            except re.error as e:
                logger.error(f"Invalid regex pattern: {str(e)}")
        
        if "email" in rule.name.lower() or config.get('pattern_type') == 'email':
            email_pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
            failed_mask |= ~col_data.str.match(email_pattern, na=False)

        if "phone" in rule.name.lower() or config.get('pattern_type') == 'phone':
            phone_pattern = r'^\+?1?\d{9,15}$'
            failed_mask |= ~col_data.str.match(phone_pattern, na=False)

        return self._create_result(rule, df, failed_mask)
    
    async def _execute_custom_sql_rule(self, rule: ValidationRule, df: pd.DataFrame) -> ValidationResult:
        """Execute custom SQL-like validation rule."""
        logger.warning("SQL rules not fully implemented for standard DataFrame source, falling back to false")
        return self._create_result(rule, df, pd.Series([False] * len(df)))
    
    def _create_result(
        self,
        rule: ValidationRule,
        df: pd.DataFrame,
        failed_mask: pd.Series,
        error_msg: Optional[str] = None,
        duplicate_col: Optional[str] = None,
    ) -> ValidationResult:
        """Create validation result from failed mask."""
        total = len(df)
        failed_count = int(failed_mask.sum())
        passed_count = total - failed_count
        
        # Get failure examples
        failure_examples = []
        if failed_count > 0:
            if duplicate_col and duplicate_col in df.columns:
                duplicate_values = df[failed_mask][duplicate_col].unique()
                failed_rows_list = []
                for val in duplicate_values[:3]:  # Max 3 duplicate groups
                    matching_rows = df[df[duplicate_col] == val]
                    failed_rows_list.append(matching_rows.head(3))
                
                if failed_rows_list:
                    failed_rows = pd.concat(failed_rows_list).head(5)
                else:
                    failed_rows = df[failed_mask].head(5)
            else:
                failed_rows = df[failed_mask].head(5)
                
            failure_examples = failed_rows.replace({pd.NA: None, pd.NaT: None}).to_dict('records')
            
            for example in failure_examples:
                for key, val in example.items():
                    if pd.isna(val):
                        example[key] = None
        
        # Determine status
        if error_msg:
            status = "error"
        elif failed_count == 0:
            status = "passed"
        elif getattr(rule, 'severity', 'warning') == "critical":
            status = "failed"
        else:
            status = "warning"
        
        return ValidationResult(
            rule_id=rule.id or "unknown",
            rule_name=rule.name,
            status=status,
            passed_count=passed_count,
            failed_count=failed_count,
            failure_examples=failure_examples,
            failure_percentage=(failed_count / total * 100) if total > 0 else 0,
            severity=getattr(rule, 'severity', 'info'),
            rule_type=getattr(rule, 'rule_type', 'unknown'),
            ai_insights=error_msg,
        )
    
    def _is_float_string(self, val: Any) -> bool:
        """Check if value can be converted to float."""
        if isinstance(val, (int, float)):
            return True
        if isinstance(val, str):
            try:
                float(val)
                return True
            except ValueError:
                return False
        return False